### ISSUE TITLE
Unexpected version of template is used if users specify template version only major or major and minor.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1891]
**What happened**:
There is a template with versions `0.1.0` and `0.10.0`.
If users specify version `0.1` using this template, users expected to use version `0.1.0`.
However, the template actually used is version `0.10.0`.

**What you expected to happen**:
Users can user correct semantic version template/command.

**How to reproduce it**:
1. Publish template with versions `0.1.0` and `0.10.0`.
2. Use this template like `template: namespace/name@0.1`.
3. The template actually used is version `0.10.0`.

**Comment by jithine** [comment]
@kumada626 Is this fixed with latest updates for template/commands sequalize queries ?

**Comment by kumada626** [comment]
I think this is not fixed yet.
I think this is not because of query problem but logic in the template/command model.
The logic of returning command version with only specified major or major and minor version is below.
https://github.com/screwdriver-cd/models/blob/8cd8d7bd419d792faa97d809271d32d372901186/lib/commandFactory.js#L143-L151
In this logic, get versions with `command.version.startsWith`.
Using this method when specifying `0.1`, `0.1.0` and `0.10.0` are `true`.
So `0.10.0` is selected by descending order.
