### ISSUE TITLE
Race condition between GitHub Webhook and Magic Branch

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#593]
With GitHub, we read from the "magic" merge branch for Pull Requests `pulls/$id/merge` to see what the contents of the `screwdriver.yaml` is.  It appears that GitHub will fire the Webhook BEFORE ensuring that the branch is in sync.  So we can get things like:

```
$ TypeError: Cannot read property 'shared' of undefined
```

When the branch isn't there yet with the screwdriver.yaml.

We should be retrying the call to GitHub to read that file based on the SHA that was sent to us by GitHub.  Basically, wait until the SHA we were asked about is there.

**Comment by petey** [comment]
I agree we should do this, but I wonder if we can also ask github to change their order of operations. Seems silly to send out a webhook when the data isn't yet available.

**Comment by stjohnjohnson** [comment]
We reached out to their support, they say these are fired asynchronously and they provide no guarantee on the order of operation. :(

**Comment by minz1027** [comment]
This same error happened to our functional-git repo very often starting 10 days ago.
https://github.com/screwdriver-cd-test/functional-git/pulls?q=is%3Apr+is%3Aclosed
build: https://beta.cd.screwdriver.cd/pipelines/151/builds/2398

**Comment by d2lam** [comment]
@stjohnjohnson Could you link the ticket you created with them and their response?

**Comment by stjohnjohnson** [comment]
Their tickets are not publicly accessible.

**Comment by d2lam** [comment]
Fixed. This should work now.

**Comment by stjohnjohnson** [comment]
Technically, this isn't fixed.  You added a 1.8s delay that _should_ catch most failures.  This is a *MAGIC* number and we should be concerned about it.  It's only going to mask the problem should there be a queue in the hook server of GitHub.
