### ISSUE TITLE
Update Checkout URL does not update SCM context

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#780]
## The Issue

When trying to update the SCM in the checkout URL from the UI, the SCM context does not update. This means that when a build is run, the build will try to checkout code from the new SCM, but the user needs to be logged into the old SCM in order to run the build. The UI also does not update which SCM the repo is in.

## What is expected

The SCM should be updated everywhere when updating it in the checkout URL.

**Comment by tkyi** [comment]
Probably just need to add a line above here (https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/update.js#L72) to update the `scmContext`. 

Should look like: `oldPipeline.scmContext = scmContext;`

**Comment by minz1027** [comment]
Should also update the url inside scmRepo too

**Comment by d2lam** [comment]
**Summary 11/21**
PR opened to fix this: https://github.com/screwdriver-cd/screwdriver/pull/805

**Comment by tkyi** [comment]
Issue is resolved.

**Comment by tk3fftk** [comment]
This issue is still remain😥
The fix of https://github.com/screwdriver-cd/screwdriver/pull/805 does not work when we transfer repository with the same branch.
GitHub provides redirecting to new organization repository from old organization repository so Screwdriver.cd can work.
But we can not update `Checkout URL`. This image is trying to update `Checkout URL` after transferring repository.
![image](https://user-images.githubusercontent.com/3445553/36462088-9d8e3b98-1704-11e8-8094-88bebda034cc.png)

Probably `scmUri` is same until change the branch.
https://github.com/screwdriver-cd/screwdriver/blob/2502db606915e6d6fc44c34f85a79648ceff4537/plugins/pipelines/update.js#L68-L74

**Comment by tkyi** [comment]
@tk3fftk This issue should be resolved now. 

We recently made a fix to resolve [the pipeline name not updating when the repo name changes](https://github.com/screwdriver-cd/screwdriver/issues/1011) with [this PR](https://github.com/screwdriver-cd/models/pull/268). You might need to sync the pipeline and refresh the page to see it.
